### PR TITLE
Add social link back to the sidnav

### PR DESCRIPTION
**Pull request by louislo-1**
modified:   angular-app/src/app/components/sidenav/sidenav.component.html
	modified:   angular-app/src/app/components/sidenav/sidenav.component.scss
	modified:   angular-app/src/app/components/sidenav/sidenav.component.ts

## This PR Closes Issue 
closes #

## What type of PR is this? (check all applicable)

- [ ] 🅰️ Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings
[Attach screenshots or recordings if applicable]

## Added to documentation?
- [ ] 📜 README.md
- [x] 🙅 no documentation needed

## [Optional] Post-deployment tasks
[Specify any post-deployment tasks that need to be performed]

## [Optional] What gif best describes this PR or how it makes you feel? 
[Embed gif or describe the feeling in plain text]

### CODE REVIEW

**Comment by copypasteov** [comment]
I am going to take over it has been a wile without activity

**Comment by copypasteov** [comment]
@louislo-1 did you not read the conversation and the code review ?

**Comment by copypasteov** [comment]
@louislo-1 if you choose to do the changes just say - I don't mind

**Comment by louislo-1** [comment]
Oh sorry it's my first issue (for a school project) and i don't see any code review, where can i see it ? I see it since 10 minutes but not before. I want to continue to work on this bug. Thanks you.

**Comment by copypasteov** [comment]
@louislo-1 ok great, sure I am going to -re-open, no worries at all and please do let us know if you need any assistance or any questions - we are here to help

**Review by monacodelisa — APPROVED** [review]

**Review by copypasteov — APPROVED** [review]

**Review by cleancodecraft — APPROVED** [review]

**Comment by monacodelisa** [comment]
@louislo-1 the person who does the code review is the one that marks the conversation as resolved, everything looks great now so I have resolved the conversations and merged, thank you for your contribution :)

**Pull request merged**
